use crate::ast::*;

grammar;

pub ConstantExp: Constant = {
    r"'[^']'" => Constant::Character((<>).chars().nth(1).unwrap()),
    r"'\\''" => Constant::Character('\''),
    r"[+-]?\d" => Constant::Integer((<>).parse().unwrap()),
    r"[+-]?\d\.\d" => Constant::Float((<>).parse().unwrap()),
    r"IGAZ|igaz" => Constant::Boolean(true),
    r"HAMIS|hamis" => Constant::Boolean(false),
};

pub Input: Constant = {
    ConstantExp
};

